services:
  mysql:
    container_name: erp-aero-mysql
    image: mysql:5.7  
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    ports:
      - 3306:3306
